codecov:
  notify:
    require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        informational: true

comment:
  require_changes: true

ignore:
  - "main.go" # Main package
  - "internal/**/*_gen.go" # Generated files
  - "internal/acctest/**/*" # Acceptance test helpers
